### ISSUE TITLE
How to port your Godot C# code into UWP app?

### ISSUE THREAD

**Issue by mediaexplorer74** [lorenzo774/FlappyBird#4]
Hi Lorenzo774,

I'm the newcomer in/at Godot theme :) I heared that Gogot is the newest milti-platform engine... 
Please tell me, how to port your FlappyBird Godot C# code into UWP app (ARM version to my old sweet Lumia phone)?
I forked your solution, started at Visual Studio and noticed that App class type is Library (not Application). So strange, indeed )) Where is application "main module"? 
I need some app.xaml+cs, mainpage xaml+cs, and Microsoft Angle library (compatible dlls ?)

Best,
MediaExplorer

P.S. Thanx for sharing/release your compiled version of FlappyBird (x86/x64, Desktop edition)  , it runs nice. =)

**Comment by lorenzo774** [comment]
Hi mediaexplorer74!

Godot has a UWP export option that unfortunately doesn't work in the Mono version.
To run the godot project you need to install the latest [Godot mono](https://godotengine.org/download/windows) version.
![img](https://i.imgur.com/yuP6l7j.png)
There is an issue on godot repo: https://github.com/godotengine/godot/issues/20271.
I'm sorry but don't know much about Microsoft Angle Library.

Thank you for the comment!

**Comment by mediaexplorer74** [comment]
> Godot has a UWP export option that unfortunately doesn't work in the Mono version. To run the godot project you need to install the latest Godot mono version. 

Ohh... I see. Non-Mono version allows UWP appx auto-creation only... ^^
I tried (yesterday) this feature with no success  :( Appx file  don't want installing (certificate bugs, etc.).
And both (Mono and Non-Mono) Godots cannot generate full C# UWP solution. 
To fix it you need provide 1-2 years of "coding/dev life" by recompiling the src code of Godot , as recomended [this docs](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_uwp.html) and creating custom Godot "exporters"/"extensions" after [Microsoft Angle C++--C# binding](https://github.com/Microsoft/angle/wiki#samplecode) . =))))
Ok, I terminated my Godot exploring. It's so hard to my mind (
But... thank you for your advice. :)

Nice to meet you,
MediaExplorer74

> Thank you for the comment!
